apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: fastapi-gateway
    app.kubernetes.io/name: fastapi-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: fastapi-gateway
  template:
    metadata:
      labels:
        app: fastapi-gateway
        app.kubernetes.io/name: fastapi-gateway
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          env:
            - name: BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bearerSecret.name }}
                  key: {{ .Values.bearerSecret.key }}
            - name: ROUTER_URL
              value: "{{ .Values.router.url }}"
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
