apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  labels:
    app: fastapi-gateway
    app.kubernetes.io/name: fastapi-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
